Create config.yml
Flixclusive/flx-providers pull request #18
Opened 2024-06-26 10:51 UTC by OshekharO

More to be added

2024-06-26 13:20 UTC, rhenwinch requested changes
Hi!

Thanks for the initiative wouldn't even think about creating github configs for this repo.

Anyway, could you re-phrase the 'extension' and 'source' words to 'provider' instead?

2024-06-26 13:20 UTC, rhenwinch commented on .github/ISSUE_TEMPLATE/request.yml
> +labels: []
Could you add the following label: provider request

2024-06-26 13:37 UTC, OshekharO commented
> Hi!
> 
> Thanks for the initiative wouldn't even think about creating github configs for this repo.
> 
> Anyway, could you re-phrase the 'extension' and 'source' words to 'provider' instead?

It just make the whole thing user-friendly and also easy for developers to get whole info

2024-06-26 16:23 UTC, OshekharO reviewed
Done

2024-06-27 03:51 UTC, rhenwinch commented on .github/ISSUE_TEMPLATE/issue.yml
> +            label: Extension information
Provider information

2024-06-27 03:52 UTC, rhenwinch approved these changes

2024-06-27 03:53 UTC, merged